/*
 * Network configuration through /etc/network/interfaces, ifup and ifdown
 *
 * (C) 2003 by thegoodguy <thegoodguy@berlios.de>
 * (C) 2011 Stefan Seyfried
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <config.h>
#include <cstdio>
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "configure_network.h"
#include <lib/libnet/libnet.h>             /* netSetNameserver */
#include <lib/libnet/network_interfaces.h> /* getInetAttributes, setInetAttributes */
#include <fstream>
#include <system/helpers.h>

#define WPA_CONFIG "/etc/wpa_supplicant.conf"

bool CNetworkConfig::canConfigure(void)
{
#ifdef ENABLE_IWD
	/* iwd brings its interfaces up and runs DHCP on them itself */
	if (wireless)
		return false;
#endif
	return !systemManaged();
}

bool CNetworkConfig::hasAutomaticStart(void)
{
	return true;
}

void CNetworkConfig::backendRead(void)
{
	inet_static = getInetAttributes(ifname, automatic_start, address, netmask, broadcast, gateway);
}

void CNetworkConfig::backendCommit(bool modified, bool nameserver_changed)
{
	if (modified)
	{
		addLoopbackDevice("lo", true);
		if (inet_static)
		{
			if (validAddress(address) && validAddress(netmask) && (gateway.empty() || validAddress(gateway)))
				setStaticAttributes(ifname, automatic_start, address, netmask, broadcast, gateway, wireless);
			else
				printf("CNetworkConfig::commitConfig: invalid address, %s not written\n", ifname.c_str());
		}
		else
			setDhcpAttributes(ifname, automatic_start, wireless);

		if (wireless && ((key != orig_key) || (ssid != orig_ssid)))
			saveWpaConfig();
	}
	if (nameserver_changed && (nameserver.empty() || validAddress(nameserver)))
		netSetNameserver(nameserver);
}

void CNetworkConfig::startNetwork(void)
{
	std::string ifup = find_executable("ifup");
	if (ifup.empty())
	{
		printf("CNetworkConfig::startNetwork: ifup not found\n");
		return;
	}
	if (!validInterface(ifname))
		return;

	my_system(2, ifup.c_str(), ifname.c_str());

	if (!inet_static)
		init_vars();
}

void CNetworkConfig::stopNetwork(void)
{
	std::string ifdown = find_executable("ifdown");
	if (ifdown.empty())
	{
		printf("CNetworkConfig::stopNetwork: ifdown not found\n");
		return;
	}
	if (!validInterface(ifname))
		return;

	my_system(2, ifdown.c_str(), ifname.c_str());
}

#ifdef ENABLE_IWD
void CNetworkConfig::readWpaConfig()
{
	ssid = "";
	key = "";
}

void CNetworkConfig::saveWpaConfig()
{
}
#else
void CNetworkConfig::readWpaConfig()
{
	std::string   s;
	std::ifstream in(WPA_CONFIG);

	ssid = "";
	key = "";
	if(!in.is_open()) {
		perror(WPA_CONFIG " read error");
		return;
	}
	while(getline(in, s)) {
		if(s[0] == '#')
			continue;
		std::string::size_type i = s.find('=');
		if (i != std::string::npos) {
			std::string n = s.substr(0, i);
			std::string val = s.substr(i + 1, s.length() - (i + 1));

			while((i = n.find(' ')) != std::string::npos)
				n.erase(i, 1);
			while((i = n.find('\t')) != std::string::npos)
				n.erase(i, 1);

			if((i = val.find('"')) != std::string::npos)
				val.erase(i, 1);
			if((i = val.rfind('"')) != std::string::npos)
				val.erase(i, 1);

			if(n == "ssid")
				ssid = val;
			else if(n == "psk")
				key = val;
		}
	}
}

/* wpa_supplicant reads a quoted string up to the last quote of the line,
 * so the only way out of it is a line break */
static bool wpa_string_ok(const std::string &s)
{
	for (size_t i = 0; i < s.length(); i++)
		if ((unsigned char)s[i] < 0x20 || s[i] == 0x7f)
			return false;
	return true;
}

void CNetworkConfig::saveWpaConfig()
{
	if (ssid.empty() || ssid.length() > 32 || !wpa_string_ok(ssid)) {
		printf("CNetworkConfig::saveWpaConfig: invalid SSID, " WPA_CONFIG " not written\n");
		return;
	}
	if (!key.empty() && (key.length() < 8 || key.length() > 63 || !wpa_string_ok(key))) {
		printf("CNetworkConfig::saveWpaConfig: invalid key, " WPA_CONFIG " not written\n");
		return;
	}

	std::string conf = "# generated by neutrino\n";
	conf += "ctrl_interface=/var/run/wpa_supplicant\n";
	conf += "\n";
	conf += "network={\n";
	conf += "	ssid=\"" + ssid + "\"\n";
	if (!key.empty()) {
		conf += "	psk=\"" + key + "\"\n";
		conf += "	proto=WPA WPA2\n";
		conf += "	key_mgmt=WPA-PSK\n";
		conf += "	pairwise=CCMP TKIP\n";
		conf += "	group=CCMP TKIP\n";
	} else {
		conf += "	key_mgmt=NONE\n";
	}
	conf += "}\n";

	/* the file holds the key, keep it to root */
	int fd = open(WPA_CONFIG, O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0600);
	if (fd < 0) {
		perror(WPA_CONFIG " write error");
		return;
	}
	if (fchmod(fd, 0600) < 0 || write(fd, conf.c_str(), conf.length()) != (ssize_t)conf.length())
		perror(WPA_CONFIG " write error");
	close(fd);
}
#endif
