/*
 * Network configuration through systemd-networkd
 *
 * One file per interface in /etc/systemd/network holds the settings made
 * here, networkd picks it up on "networkctl reload".
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <config.h>
#include <arpa/inet.h>
#include <cstdio>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "configure_network.h"
#include <lib/libnet/libnet.h>
#include <fstream>
#include <system/helpers.h>

#define NETWORKD_CONFIG_DIR "/etc/systemd/network"
/* sorts before the distribution's catch-all files such as 80-wired.network */
#define NETWORKD_CONFIG_PREFIX "50-neutrino-"
#define NETWORKD_RUNTIME_DIR "/run/systemd/netif"

static std::string config_file(const std::string &ifname)
{
	return std::string(NETWORKD_CONFIG_DIR "/" NETWORKD_CONFIG_PREFIX) + ifname + ".network";
}

static std::string trim(const std::string &s)
{
	std::string::size_type b = s.find_first_not_of(" \t\r");
	if (b == std::string::npos)
		return "";
	return s.substr(b, s.find_last_not_of(" \t\r") - b + 1);
}

static int netmask_to_prefix(const std::string &netmask)
{
	struct in_addr in;
	if (inet_pton(AF_INET, netmask.c_str(), &in) != 1)
		return -1;

	uint32_t m = ntohl(in.s_addr);
	int prefix = 0;
	while (m & 0x80000000u)
	{
		prefix++;
		m <<= 1;
	}
	/* the bits of a netmask are contiguous */
	return m ? -1 : prefix;
}

static std::string prefix_to_netmask(int prefix)
{
	if (prefix < 0 || prefix > 32)
		return "";

	struct in_addr in;
	in.s_addr = htonl(prefix ? 0xffffffffu << (32 - prefix) : 0);
	char buf[INET_ADDRSTRLEN];
	return inet_ntop(AF_INET, &in, buf, sizeof(buf)) ? buf : "";
}

bool CNetworkConfig::canConfigure(void)
{
	/* a wireless interface is left to the wireless daemon */
	if (wireless)
		return false;
	if (systemManaged())
		return false;
	return access(NETWORKD_RUNTIME_DIR, F_OK) == 0;
}

bool CNetworkConfig::hasAutomaticStart(void)
{
	return false;
}

void CNetworkConfig::backendRead(void)
{
	inet_static = false;
	automatic_start = true;

	std::ifstream in(config_file(ifname).c_str());
	if (!in.is_open())
		return;

	std::string line, section, _address, _netmask, _gateway, _nameserver;
	bool dhcp = false;
	while (getline(in, line))
	{
		line = trim(line);
		if (line.empty() || line[0] == '#' || line[0] == ';')
			continue;
		if (line[0] == '[')
		{
			section = line;
			continue;
		}
		std::string::size_type eq = line.find('=');
		if (eq == std::string::npos || section != "[Network]")
			continue;

		std::string name = trim(line.substr(0, eq));
		std::string value = trim(line.substr(eq + 1));
		if (name == "DHCP")
			dhcp = (value == "yes" || value == "ipv4" || value == "true");
		else if (name == "Address" && _address.empty())
		{
			std::string::size_type slash = value.find('/');
			if (slash == std::string::npos)
				continue;
			std::string a = value.substr(0, slash);
			std::string m = prefix_to_netmask(atoi(value.substr(slash + 1).c_str()));
			if (validAddress(a) && !m.empty())
			{
				_address = a;
				_netmask = m;
			}
		}
		else if (name == "Gateway" && _gateway.empty() && validAddress(value))
			_gateway = value;
		else if (name == "DNS" && _nameserver.empty() && validAddress(value))
			_nameserver = value;
	}

	if (dhcp || _address.empty())
		return;

	inet_static = true;
	address = _address;
	netmask = _netmask;
	gateway = _gateway;
	nameserver = _nameserver;

	struct in_addr a, m;
	inet_pton(AF_INET, address.c_str(), &a);
	inet_pton(AF_INET, netmask.c_str(), &m);
	a.s_addr |= ~m.s_addr;
	char buf[INET_ADDRSTRLEN];
	broadcast = inet_ntop(AF_INET, &a, buf, sizeof(buf)) ? buf : "";
}

void CNetworkConfig::backendCommit(bool modified, bool nameserver_changed)
{
	if (!modified && !nameserver_changed)
		return;

	if (!validInterface(ifname))
		return;

	std::string conf = "# generated by neutrino\n";
	conf += "[Match]\n";
	conf += "Name=" + ifname + "\n";
	conf += "\n";
	conf += "[Link]\n";
	conf += "RequiredForOnline=no\n";
	conf += "\n";
	conf += "[Network]\n";
	if (inet_static)
	{
		int prefix = netmask_to_prefix(netmask);
		if (!validAddress(address) || prefix < 0 ||
		    (!gateway.empty() && !validAddress(gateway)) ||
		    (!nameserver.empty() && !validAddress(nameserver)))
		{
			printf("CNetworkConfig::commitConfig: invalid address, %s not written\n", ifname.c_str());
			return;
		}
		char p[16];
		snprintf(p, sizeof(p), "/%d", prefix);
		conf += "Address=" + address + p + "\n";
		if (!gateway.empty())
			conf += "Gateway=" + gateway + "\n";
		if (!nameserver.empty())
			conf += "DNS=" + nameserver + "\n";
	}
	else
	{
		conf += "DHCP=yes\n";
		conf += "\n";
		conf += "[DHCP]\n";
		conf += "UseMTU=yes\n";
		conf += "RouteMetric=10\n";
		conf += "ClientIdentifier=mac\n";
	}

	if (mkdir(NETWORKD_CONFIG_DIR, 0755) < 0 && errno != EEXIST)
	{
		perror(NETWORKD_CONFIG_DIR);
		return;
	}

	/* networkd only reads *.network, the temporary name is invisible to it */
	std::string file = config_file(ifname);
	std::string tmp = file + ".new";
	unlink(tmp.c_str());
	int fd = open(tmp.c_str(), O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW | O_CLOEXEC, 0644);
	if (fd < 0)
	{
		perror(tmp.c_str());
		return;
	}
	bool ok = write(fd, conf.c_str(), conf.length()) == (ssize_t)conf.length();
	ok = (fchmod(fd, 0644) == 0) && ok;
	ok = (fsync(fd) == 0) && ok;
	close(fd);
	if (!ok || rename(tmp.c_str(), file.c_str()) < 0)
	{
		perror(file.c_str());
		unlink(tmp.c_str());
	}
}

void CNetworkConfig::startNetwork(void)
{
	if (!canConfigure() || !validInterface(ifname))
		return;

	std::string networkctl = find_executable("networkctl");
	if (networkctl.empty())
	{
		printf("CNetworkConfig::startNetwork: networkctl not found\n");
		return;
	}

	my_system(2, networkctl.c_str(), "reload");
	my_system(3, networkctl.c_str(), "reconfigure", ifname.c_str());

	if (inet_static)
		return;

	/* give the DHCP client a moment, the menu shows the address next */
	for (int i = 0; i < 32; i++)
	{
		std::string ip, mask, brd;
		netGetIP(ifname, ip, mask, brd);
		if (!ip.empty() && ip != "0.0.0.0")
			break;
		usleep(250000);
	}
	init_vars();
}

void CNetworkConfig::stopNetwork(void)
{
	/* networkd replaces the running setup on reconfigure */
}

void CNetworkConfig::readWpaConfig()
{
	ssid = "";
	key = "";
}

void CNetworkConfig::saveWpaConfig()
{
}
