installdir = $(THEMESDIR)/Meridian/icons

install_DATA = \
	btn_blue.png \
	btn_checked.png \
	btn_green.png \
	btn_option_off_active.png \
	btn_option_off_inactive.png \
	btn_option_on_active.png \
	btn_option_on_inactive.png \
	btn_red.png \
	btn_yellow.png \
	down.png \
	dummy.png \
	dummy_small.png \
	left.png \
	right.png \
	slider_alpha.png \
	slider_blue.png \
	slider_body.png \
	slider_body_progress.png \
	slider_green.png \
	slider_inactive.png \
	slider_red.png \
	up.png
