#! /usr/bin/perl

# This proggie takes a (possibly outdated) locale file as its (only)
# argument, and creates a new version, with `-work` appended. The thus
# created tile contains all keys of the master file, and is intended
# to, after manual editing, replace the outdated locale file.

# Written by Barf on 2005-12-10.
# reorganized by Stefan Seyfried 2016-01-03, following changes:
#  * use strict, use warnings to find errors easier
#  * make it work with the above pragmas
#  * tolerance against empty locales in deutsch.locale

use warnings;
use strict;
use File::Basename qw(dirname);

$#ARGV == 0 || die("Usage: create-locale-work file.locale\n");

my $no_errors = 0;
my $localefilename = $ARGV[0];
my $masterfilename = dirname($localefilename) . "/deutsch.locale";
my $outfilename = $localefilename . "-work";

sub read_locale_file
{
	my ($filename) = @_;
	my %entries;
	my $line_number = 0;

	open(my $fh, "<", $filename) || die("Could not open locale file $filename");

	while (my $line = <$fh>)
	{
		$line_number++;
		chomp $line;
		$line =~ s/^\s+//; # strip whitespace from start of line
		next if $line eq "";

		my ($key, $text) = split /\s+/, $line, 2;
		defined $key || next;
		exists $entries{$key} && die("Duplicate locale key '$key' in $filename line $line_number\n");
		$entries{$key} = $text ? $text : "";
	}

	close($fh);
	return %entries;
}

my %master = read_locale_file($masterfilename);
my %locale = read_locale_file($localefilename);

unlink($outfilename);
open(my $out, ">", $outfilename) || die("Could not open output file $outfilename");

foreach my $term (sort keys %master)
{
	if (exists $locale{$term})
	{
		print $out $term." ".$locale{$term}."\n";
	}
	else
	{
		# not found
		$no_errors++;
		print $out $term." (((T))) ".$master{$term}."\n";
	}
}

close($out);

if ($no_errors == 0)
{
	unlink($outfilename);
}
else
{
	print "There were ", $no_errors, " error(s) in ", $localefilename, ".\n";
}
