#define SCANMODE_OPTION_COUNT 3
const CMenuOptionChooser::keyval SCANMODE_OPTIONS[SCANMODE_OPTION_COUNT] =
{
        { 0,    LOCALE_EXTRA_SCAN_FULL,0},
        { 1,    LOCALE_EXTRA_SCAN_FAST,0},
        { 2,    LOCALE_EXTRA_TPSCAN,0}
};

#define HDD_NOISE_OPTION_COUNT 4
const CMenuOptionChooser::keyval HDD_NOISE_OPTIONS[HDD_NOISE_OPTION_COUNT] =
{
	{0, LOCALE_OPTIONS_OFF ,0 },
	{128, LOCALE_HDD_SLOW ,0 },
	{190, LOCALE_HDD_MIDDLE ,0 },
	{254, LOCALE_HDD_FAST ,0 }
};
#define HDD_FILESYS_OPTION_COUNT 3
const CMenuOptionChooser::keyval HDD_FILESYS_OPTIONS[HDD_FILESYS_OPTION_COUNT] =
{
	{0, LOCALE_HDD_EXT3 ,0 },
	{1, LOCALE_HDD_REISER ,0 },
	{2, LOCALE_OPTIONS_OFF ,0 }
};
#define HDD_SLEEP_OPTION_COUNT 7
const CMenuOptionChooser::keyval HDD_SLEEP_OPTIONS[HDD_SLEEP_OPTION_COUNT] =
{
	{0, LOCALE_OPTIONS_OFF ,0 },
	{12, LOCALE_HDD_1MIN ,0 },
	{60, LOCALE_HDD_5MIN ,0 },
	{120, LOCALE_HDD_10MIN ,0 },
	{240, LOCALE_HDD_20MIN ,0 },
	{241, LOCALE_HDD_30MIN ,0 },
	{242, LOCALE_HDD_60MIN ,0 }
};
#if 0
#define LOGO_OPTION_COUNT 3
const CMenuOptionChooser::keyval LOGO_OPTIONS[LOGO_OPTION_COUNT] =
{
	{1, LOCALE_EXTRA_LOGO1 ,0 },
	{2, LOCALE_EXTRA_LOGO2 ,0 },
	{3, LOCALE_EXTRA_LOGO3 ,0 }
};
#endif
#define RF_CARRIER_OPTION_COUNT 4
const CMenuOptionChooser::keyval RF_CARRIER_OPTIONS[RF_CARRIER_OPTION_COUNT] =
{
	{0, LOCALE_RF_CARRIER_4500 ,0 },
	{1, LOCALE_RF_CARRIER_5500 ,0 },
	{2, LOCALE_RF_CARRIER_6000 ,0 },
	{3, LOCALE_RF_CARRIER_6500 ,0 }
};
#define OPTIONS_SOUTH0_NORTH1_OPTION_COUNT 2
const CMenuOptionChooser::keyval OPTIONS_SOUTH0_NORTH1_OPTIONS[OPTIONS_SOUTH0_NORTH1_OPTION_COUNT] =
{
	{0, LOCALE_EXTRA_SOUTH ,0 },
	{1, LOCALE_EXTRA_NORTH ,0 }
};
#define OPTIONS_EAST0_WEST1_OPTION_COUNT 2
const CMenuOptionChooser::keyval OPTIONS_EAST0_WEST1_OPTIONS[OPTIONS_EAST0_WEST1_OPTION_COUNT] =
{
	{0, LOCALE_EXTRA_EAST ,0 },
	{1, LOCALE_EXTRA_WEST ,0 }
};
